
export enum BookingStatus {
  REQUESTED = 'REQUESTED',
  ACCEPTED = 'ACCEPTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED_BY_PROVIDER = 'COMPLETED_BY_PROVIDER',
  CONFIRMED_BY_CLIENT = 'CONFIRMED_BY_CLIENT',
  SETTLED = 'SETTLED',
  AUTO_SETTLED = 'AUTO_SETTLED',
  EXPIRED = 'EXPIRED',
  CANCELLED = 'CANCELLED',
  DISPUTED = 'DISPUTED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentStatus {
    PENDING = "PENDING",
    COMPLETED = "COMPLETED",
    FAILED = "FAILED",
    CANCELLED = "CANCELLED",
    REFUNDED = "REFUNDED",
    PARTIAL_REFUNDED = "PARTIAL_REFUNDED",
    PAID = "PAID",
    PROVIDER_CANCELLED = "PROVIDER_CANCELLED",
    SETTLED = "SETTLED",
};
 
