
export enum BookingStatus {
  REQUESTED = 'REQUESTED',
  ACCEPTED = 'ACCEPTED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED_BY_PROVIDER = 'COMPLETED_BY_PROVIDER',
  SETTLED = 'SETTLED',
  AUTO_SETTLED = 'AUTO_SETTLED',
  CANCELLED = 'CANCELLED',
  DISPUTED = 'DISPUTED'
}

export enum PaymentStatus {
    REFUNDED = "REFUNDED",
    PARTIAL_REFUNDED = "PARTIAL_REFUNDED",
    PAID = "PAID",
};
 
